import pygame

#Screen dimension
WIDTH = 1170
HEIGHT = 650

#Main board dimension
ROWS = 10
COLS = 13
BOARD_WIDTH = 1170
BOARD_HEIGHT = 650
RECT_WIDTH = BOARD_WIDTH // COLS
RECT_HEIGHT = BOARD_HEIGHT // ROWS
SPECIAL_POSITION = [(4, 2), (4, 3), (5, 2), (5, 3), (4, 6), (4, 7), (5, 6), (5, 7)]

#Black's clock
BC_ROWS = 1
BC_COLS = 3
BC_WIDTH = 270
BC_HEIGHT = 65
BC_RECT_WIDTH = BC_WIDTH // BC_COLS
BC_RECT_HEIGHT = BC_HEIGHT // BC_ROWS

#Reds's clock
RC_ROWS = 1
RC_COLS = 3
RC_WIDTH = 270
RC_HEIGHT = 65
RC_RECT_WIDTH = RC_WIDTH // RC_COLS
RC_RECT_HEIGHT = RC_HEIGHT // RC_ROWS
